# Generated by Django 5.2.4 on 2026-08-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploads/images/'),
        ),
    ]
